name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.PAT_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          
  build-and-upload:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.release-please.outputs.tag_name }}
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Set encoding
        run: |
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          $env:DOTNET_SYSTEM_GLOBALIZATION_INVARIANT = "false"
        shell: pwsh
        
      - name: Restore dependencies
        run: dotnet restore
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
        
      - name: Build app (self-contained)
        run: dotnet publish EasyRCP.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:InvariantGlobalization=false -o publish
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
        
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: publish/*.exe
          tag_name: ${{ needs.release-please.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
